### ISSUE TITLE
Improve Website Content

### ISSUE THREAD

**Issue by Praful932** [Praful932/Edutopia#3]
Any minor changes with respect to the website content, Please document your changes before making them. Thank you!

**Comment by akankshast** [comment]
Please assign this issue to me. I will try my best to improve it.

Regards
Akanksha😁

**Comment by Praful932** [comment]
@akankshast I have updated the description. Please check. Thank you

**Comment by akankshast** [comment]
Noted!

**Comment by Praful932** [comment]
@akankshast Updates?
