### ISSUE TITLE
Add Chat functionality between users

### ISSUE THREAD

**Issue by Praful932** [Praful932/Edutopia#4]
There are two kinds of User Currently Students & Mentors. A Chat functionality would be nice so both of them can communicate asynchronously. This can be done using something like [django-channels](https://channels.readthedocs.io/en/latest/). Please document your approach before working on it. Thank you!

**Comment by Cirediallo** [comment]
can you more elaborate ?

**Comment by Praful932** [comment]
@Cirediallo I have update the description.
