### ISSUE TITLE
Make Unresponsive Pages Responsive

### ISSUE THREAD

**Issue by Praful932** [Praful932/Edutopia#5]
Any minor changes with respect to how the page looks on mobile devices. Please document your changes before making them. Thank you!

**Comment by lukicenturi** [comment]
can you assign me please?

**Comment by anurawat01** [comment]
I would Like to work on this issue! As I have so much experience in BOOTSTRAP?

**Comment by Praful932** [comment]
@anurawat01 If you have experience with django you can work on #4

**Comment by boy-who-codes** [comment]
i will try

**Comment by Praful932** [comment]
@anurawat01 Would you like to work on this?

**Comment by anurawat01** [comment]
@Praful932 Yeah Sure.... I would love to do!

**Comment by Praful932** [comment]
@anurawat01 Updates?
